<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="WebForm4.aspx.cs" Inherits="Assignment_15.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="av_section_1" class="avia-section main_color avia-section-small avia-no-border-styling avia-bg-style-scroll  avia-builder-el-0  el_before_av_section  avia-builder-el-first  av-minimum-height av-minimum-height-custom container_wrap fullsize" data-section-bg-repeat="no-repeat" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 0px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-image: url(&quot;http://www.optimusinfo.com/wp-content/uploads/2014/11/optimus-careers-heading-sm.jpg&quot;); background-attachment: scroll; background-color: rgb(255, 255, 255); background-position: left top; background-repeat: no-repeat;">
    <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px; z-index: 1; opacity: 1; transition: opacity 0.6s ease-in; display: table; height: 250px;">
        <main role="main" itemprop="mainContentOfPage" class="template-page content  av-content-full alpha units" style="box-sizing: content-box; float: none !important; display: table-cell; margin: 0px auto; position: relative; z-index: 1; min-height: 1px; padding-top: 20px; padding-bottom: 20px; border: none; clear: left; width: 1163px; vertical-align: middle; height: 209.594px; padding-left: 0px;">
        <div class="post-entry post-entry-type-page post-entry-5760" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                <div class="avia-button-wrap avia-button-center  avia-builder-el-3  el_after_av_hr  avia-builder-el-last " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; text-align: center; clear: both;">
                    <a class="avia-button  avia-icon_select-no avia-color-light avia-size-medium avia-position-center " href="http://www.optimusinfo.com/careers/#openings" style="box-sizing: border-box; margin: 3px 0px; padding: 12px 16px 10px; border: 3px solid rgb(255, 255, 255); font-style: inherit; font-variant: inherit; font-weight: normal; font-stretch: inherit; font-size: 13px; line-height: 1.2em; font-family: inherit; vertical-align: baseline; text-decoration: none; outline: 0px; max-width: 100%; color: rgb(255, 255, 255); border-radius: 3px; display: inline-block; position: relative; text-align: center; min-width: 90px; background: transparent;"><span class="avia_iconbox_title" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">View Current Openings</span></a></div>
            </div>
        </div>
        </main>
    </div>
</div>
<div id="av_section_2" class="avia-section main_color avia-section-small avia-no-border-styling avia-bg-style-scroll  avia-builder-el-4  el_after_av_section  el_before_av_section  container_wrap fullsize" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 0px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px;">
        <div class="template-page content  av-content-full alpha units" style="box-sizing: content-box; margin: 0px auto; padding: 20px 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; display: inline; position: relative; z-index: 1; min-height: 1px; clear: left; width: 1163px;">
            <div class="post-entry post-entry-type-page post-entry-5760" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <h2 style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 36px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(51, 51, 51); text-transform: none; letter-spacing: 1px; text-align: center;">Optimus is:</h2>
                        </div>
                    </section>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: center;">
                                A young organization who believes the winning combination for success is passion, speed, hard work and strong belief in customer satisfaction.<br style="box-sizing: border-box;" />
                                If you believe in this combination, feel free to connect with us.</p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="av_section_3" class="avia-section main_color avia-section-small avia-no-border-styling avia-bg-style-scroll  avia-builder-el-7  el_after_av_section  el_before_av_section  container_wrap fullsize" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 0px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 241, 241);">
    <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px;">
        <div class="template-page content  av-content-full alpha units" style="box-sizing: content-box; margin: 0px auto; padding: 20px 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; display: inline; position: relative; z-index: 1; min-height: 1px; clear: left; width: 1163px;">
            <div class="post-entry post-entry-type-page post-entry-5760" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <h2 style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 36px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(51, 51, 51); text-transform: none; letter-spacing: 1px; text-align: center;">We are:</h2>
                        </div>
                    </section>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: center;">
                                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">A dynamic and passionate group of professionals who love the world of software development, testing, business intelligence, and mobile applications.</span></p>
                        </div>
                    </section>
                    <div class="hr hr-invisible  avia-builder-el-10  el_after_av_textblock  el_before_av_textblock " style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 25px; font-family: inherit; vertical-align: baseline; clear: both; display: block; width: 1163px; height: 30px; position: relative; float: none;">
                        <span class="hr-inner " style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; height: 1px; left: 0px; top: 15px; width: 1163px;"><span class="hr-inner-style" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span></span>
                    </div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <h2 style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 36px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(51, 51, 51); text-transform: none; letter-spacing: 1px; text-align: center;">We like:</h2>
                        </div>
                    </section>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: center;">
                                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">An acute eye for details, diligence and drive, collaborative team spirit, and, most importantly, a strong desire for customer satisfaction and fostering long-lasting client relationships.</span></p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="av_section_4" class="avia-section main_color avia-section-small avia-no-border-styling avia-bg-style-scroll  avia-builder-el-13  el_after_av_section  el_before_av_section  container_wrap fullsize" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 0px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px;">
        <div class="template-page content  av-content-full alpha units" style="box-sizing: content-box; margin: 0px auto; padding: 20px 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; display: inline; position: relative; z-index: 1; min-height: 1px; clear: left; width: 1163px;">
            <div class="post-entry post-entry-type-page post-entry-5760" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                        <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                            <h2 style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 36px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(51, 51, 51); text-transform: none; letter-spacing: 1px; text-align: center;">What we offer:</h2>
                        </div>
                    </section>
                    <div class="flex_column av_one_half first  avia-builder-el-15  el_after_av_textblock  el_before_av_one_half  column-top-margin" style="box-sizing: border-box; margin: 50px 0px 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; z-index: 1; float: left; position: relative; min-height: 1px; width: 546.609px; clear: left;">
                        <div class="avia-icon-list-container  avia-builder-el-16  avia-builder-el-no-sibling " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; clear: both;">
                            <ul class="avia-icon-list avia-icon-list-left avia_animate_when_almost_visible avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: disc outside;">
                                <li class="avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 30px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style-type: none; list-style-position: outside; clear: both; position: relative; min-height: 60px; text-indent: 0px;">
                                    <div class="iconlist_icon avia-font-entypo-fontello" style="box-sizing: border-box; margin: 0px 30px 0px 2px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 64px; font-family: entypo-fontello; vertical-align: baseline; height: 64px; width: 64px; text-align: center; border-radius: 500px; position: relative; float: left; z-index: 5; color: rgb(255, 255, 255); opacity: 1; transform: scale(1); animation: avia_appear 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1; background-color: rgb(251, 0, 0);">
                                        <span aria-hidden="true" class="iconlist-char" data-av_icon="" data-av_iconfont="entypo-fontello" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span>
                                    </div>
                                    <article class="article-icon-entry " itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; min-height: 45px;">
                                        <div class="iconlist_content_wrap" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; min-height: 1.5em;">
                                            <header class="entry-content-header" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                                <h4 class="iconlist_title" itemprop="headline" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 18px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34); text-transform: uppercase; top: 4px; position: relative;"></h4>
                                            </header>
                                            <div class="iconlist_content " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                                    <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">A progressive and fast-paced work environment</span></p>
                                            </div>
                                        </div>
                                        <footer class="entry-footer" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                        </footer>
                                    </article>
                                    <div class="iconlist-timeline" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-right-style: dashed; border-color: rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0.796875px; left: 32px; width: 1px; height: 80.7813px; animation: avia_slide_down 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1;">
                                    </div>
                                </li>
                                <li class="avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 30px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style-type: none; list-style-position: outside; clear: both; position: relative; min-height: 60px; text-indent: 0px;">
                                    <div class="iconlist_icon avia-font-entypo-fontello" style="box-sizing: border-box; margin: 0px 30px 0px 2px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 64px; font-family: entypo-fontello; vertical-align: baseline; height: 64px; width: 64px; text-align: center; border-radius: 500px; position: relative; float: left; z-index: 5; color: rgb(255, 255, 255); opacity: 1; transform: scale(1); animation: avia_appear 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1; background-color: rgb(251, 0, 0);">
                                        <span aria-hidden="true" class="iconlist-char" data-av_icon="" data-av_iconfont="entypo-fontello" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span>
                                    </div>
                                    <article class="article-icon-entry " itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; min-height: 45px;">
                                        <div class="iconlist_content_wrap" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; min-height: 1.5em;">
                                            <header class="entry-content-header" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                                <h4 class="iconlist_title" itemprop="headline" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 18px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34); text-transform: uppercase; top: 4px; position: relative;"></h4>
                                            </header>
                                            <div class="iconlist_content " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                                    Central Vancouver location close to transit and restaurants.</p>
                                            </div>
                                        </div>
                                        <footer class="entry-footer" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                        </footer>
                                    </article>
                                    <div class="iconlist-timeline" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-right-style: dashed; border-color: rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0.796875px; left: 32px; width: 1px; height: 80.7813px; animation: avia_slide_down 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1;">
                                    </div>
                                </li>
                                <li class="avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 30px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style-type: none; list-style-position: outside; clear: both; position: relative; min-height: 60px; text-indent: 0px;">
                                    <div class="iconlist_icon avia-font-entypo-fontello" style="box-sizing: border-box; margin: 0px 30px 0px 2px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 64px; font-family: entypo-fontello; vertical-align: baseline; height: 64px; width: 64px; text-align: center; border-radius: 500px; position: relative; float: left; z-index: 5; color: rgb(255, 255, 255); opacity: 1; transform: scale(1); animation: avia_appear 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1; background-color: rgb(251, 0, 0);">
                                        <span aria-hidden="true" class="iconlist-char" data-av_icon="" data-av_iconfont="entypo-fontello" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span>
                                    </div>
                                    <article class="article-icon-entry " itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; min-height: 45px;">
                                        <div class="iconlist_content_wrap" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; min-height: 1.5em;">
                                            <header class="entry-content-header" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                                <h4 class="iconlist_title" itemprop="headline" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 18px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34); text-transform: uppercase; top: 4px; position: relative;"></h4>
                                            </header>
                                            <div class="iconlist_content " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                                    Having the opportunity to work on diverse and challenging projects.</p>
                                            </div>
                                        </div>
                                        <footer class="entry-footer" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                        </footer>
                                    </article>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="flex_column av_one_half   avia-builder-el-17  el_after_av_one_half  avia-builder-el-last  column-top-margin" style="box-sizing: border-box; margin: 50px 0px 0px 69.7656px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; z-index: 1; float: left; position: relative; min-height: 1px; width: 546.609px;">
                        <div class="avia-icon-list-container  avia-builder-el-18  avia-builder-el-no-sibling " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; clear: both;">
                            <ul class="avia-icon-list avia-icon-list-left avia_animate_when_almost_visible avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: disc outside;">
                                <li class="avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 30px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style-type: none; list-style-position: outside; clear: both; position: relative; min-height: 60px; text-indent: 0px;">
                                    <div class="iconlist_icon avia-font-entypo-fontello" style="box-sizing: border-box; margin: 0px 30px 0px 2px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 64px; font-family: entypo-fontello; vertical-align: baseline; height: 64px; width: 64px; text-align: center; border-radius: 500px; position: relative; float: left; z-index: 5; color: rgb(255, 255, 255); opacity: 1; transform: scale(1); animation: avia_appear 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1; background-color: rgb(251, 0, 0);">
                                        <span aria-hidden="true" class="iconlist-char" data-av_icon="" data-av_iconfont="entypo-fontello" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span>
                                    </div>
                                    <article class="article-icon-entry " itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; min-height: 45px;">
                                        <div class="iconlist_content_wrap" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; min-height: 1.5em;">
                                            <header class="entry-content-header" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                                <h4 class="iconlist_title" itemprop="headline" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 18px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34); text-transform: uppercase; top: 4px; position: relative;"></h4>
                                            </header>
                                            <div class="iconlist_content " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                                    Competitive compensation with medical, life and dental benefits.</p>
                                            </div>
                                        </div>
                                        <footer class="entry-footer" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                        </footer>
                                    </article>
                                    <div class="iconlist-timeline" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-right-style: dashed; border-color: rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0.796875px; left: 32px; width: 1px; height: 80.7813px; animation: avia_slide_down 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1;">
                                    </div>
                                </li>
                                <li class="avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 30px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style-type: none; list-style-position: outside; clear: both; position: relative; min-height: 60px; text-indent: 0px;">
                                    <div class="iconlist_icon avia-font-entypo-fontello" style="box-sizing: border-box; margin: 0px 30px 0px 2px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 64px; font-family: entypo-fontello; vertical-align: baseline; height: 64px; width: 64px; text-align: center; border-radius: 500px; position: relative; float: left; z-index: 5; color: rgb(255, 255, 255); opacity: 1; transform: scale(1); animation: avia_appear 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1; background-color: rgb(251, 0, 0);">
                                        <span aria-hidden="true" class="iconlist-char" data-av_icon="" data-av_iconfont="entypo-fontello" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span>
                                    </div>
                                    <article class="article-icon-entry " itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; min-height: 45px;">
                                        <div class="iconlist_content_wrap" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; min-height: 1.5em;">
                                            <header class="entry-content-header" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                                <h4 class="iconlist_title" itemprop="headline" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 18px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34); text-transform: uppercase; top: 4px; position: relative;"></h4>
                                            </header>
                                            <div class="iconlist_content " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                                    <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Opportunity to grow and work with a driven and experienced team.</span></p>
                                            </div>
                                        </div>
                                        <footer class="entry-footer" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                        </footer>
                                    </article>
                                    <div class="iconlist-timeline" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-right-style: dashed; border-color: rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0.796875px; left: 32px; width: 1px; height: 80.7813px; animation: avia_slide_down 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1;">
                                    </div>
                                </li>
                                <li class="avia_start_animation" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 30px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style-type: none; list-style-position: outside; clear: both; position: relative; min-height: 60px; text-indent: 0px;">
                                    <div class="iconlist_icon avia-font-entypo-fontello" style="box-sizing: border-box; margin: 0px 30px 0px 2px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 64px; font-family: entypo-fontello; vertical-align: baseline; height: 64px; width: 64px; text-align: center; border-radius: 500px; position: relative; float: left; z-index: 5; color: rgb(255, 255, 255); opacity: 1; transform: scale(1); animation: avia_appear 1s cubic-bezier(0.175, 0.885, 0.32, 1.275) 1; background-color: rgb(251, 0, 0);">
                                        <span aria-hidden="true" class="iconlist-char" data-av_icon="" data-av_iconfont="entypo-fontello" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"></span>
                                    </div>
                                    <article class="article-icon-entry " itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; min-height: 45px;">
                                        <div class="iconlist_content_wrap" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; min-height: 1.5em;">
                                            <header class="entry-content-header" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                                                <h4 class="iconlist_title" itemprop="headline" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 18px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34); text-transform: uppercase; top: 4px; position: relative;"></h4>
                                            </header>
                                            <div class="iconlist_content " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                                    Ability&nbsp;to work with&nbsp;<span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">industry leading clients&nbsp;from around the world.</span></p>
                                            </div>
                                        </div>
                                    </article>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</asp:Content>
