<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="Assignment_15.WebForm2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="av_section_1" class="avia-section main_color avia-section-small avia-no-border-styling avia-bg-style-scroll  avia-builder-el-0  el_before_av_section  avia-builder-el-first  av-minimum-height av-minimum-height-custom container_wrap fullsize" data-section-bg-repeat="no-repeat" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 0px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-image: url(&quot;http://www.optimusinfo.com/wp-content/uploads/2014/11/optimus-company-heading-small.jpg&quot;); background-attachment: scroll; background-color: rgb(255, 255, 255); background-position: left top; background-repeat: no-repeat;">
        <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px; z-index: 1; opacity: 1; transition: opacity 0.6s ease-in; display: table; height: 250px;">
            <main role="main" itemprop="mainContentOfPage" class="template-page content  av-content-full alpha units" style="box-sizing: content-box; float: none !important; display: table-cell; margin: 0px auto; position: relative; z-index: 1; min-height: 1px; padding-top: 20px; padding-bottom: 20px; border: none; clear: left; width: 1163px; vertical-align: middle; height: 209.594px; padding-left: 0px;">
            <div class="post-entry post-entry-type-page post-entry-5754" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                    <div class="avia-button-wrap avia-button-center  avia-builder-el-3  el_after_av_hr  avia-builder-el-last " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; text-align: center; clear: both;">
                        <a class="avia-button  avia-icon_select-no avia-color-light avia-size-medium avia-position-center " href="http://www.optimusinfo.com/contact-us/" style="box-sizing: border-box; margin: 3px 0px; padding: 12px 16px 10px; border: 3px solid rgb(255, 255, 255); font-style: inherit; font-variant: inherit; font-weight: normal; font-stretch: inherit; font-size: 13px; line-height: 1.2em; font-family: inherit; vertical-align: baseline; text-decoration: none; outline: 0px; max-width: 100%; color: rgb(255, 255, 255); border-radius: 3px; display: inline-block; position: relative; text-align: center; min-width: 90px; background: transparent;"><span class="avia_iconbox_title" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Contact Us About Your Next Project</span></a></div>
                </div>
            </div>
            </main>
        </div>
    </div>
    <div id="av_section_2" class="avia-section main_color avia-section-small avia-no-shadow avia-bg-style-scroll  avia-builder-el-4  el_after_av_section  el_before_av_section  container_wrap fullsize" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-color: rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 0px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px;">
            <div class="template-page content  av-content-full alpha units" style="box-sizing: content-box; margin: 0px auto; padding: 20px 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; display: inline; position: relative; z-index: 1; min-height: 1px; clear: left; width: 1163px;">
                <div class="post-entry post-entry-type-page post-entry-5754" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                    <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                        <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                            <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                    Optimus is designed to help global organizations address their information needs. The world of information is changing and so are the methods of managing it. We provide outsourced technology services to mid-sized organizations who&nbsp;have different needs than Fortune 500 companies. Optimus is designed to meet these&nbsp;specific&nbsp;needs.</p>
                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                    The demand for outsourced technology services is increasing as organizations seek to increase their efficiency. This trend has been improved through advancements in technology and telecommunications that now allow outsourcing services to offer seamless services all over the globe.</p>
                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                    Though outsourcing is a maturing market, mid-sized software companies and enterprises often struggle to find a reliable, nimble, and capable outsourcing vendor. Optimus has the right mix of size, flexibility, and experience to provide high quality outsourcing solutions to mid-sized software companies and enterprises.</p>
                                <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                    Optimus is headquartered in Vancouver, Canada and has delivery centers in Canada and India. The founders of Optimus have extensive experience running large global outsourcing companies.</p>
                                <h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 20px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(251, 0, 0);"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: inherit;">Optimus Core Values:</strong></h3>
                                <ul style="box-sizing: border-box; margin: 0px 0px 20px 7px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: disc outside;">
                                    <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-indent: 0px;">Universal Entrepreneurial Spirit</li>
                                    <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-indent: 0px;">Absolute Customer Satisfaction</li>
                                    <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-indent: 0px;">Self Led</li>
                                    <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-indent: 0px;">High Intellectual Capital</li>
                                    <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-indent: 0px;">Work Life Integration</li>
                                    <li style="box-sizing: border-box; margin: 0px 0px 0px 1em; padding: 3px 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-indent: 0px;">Celebrate Success</li>
                                </ul>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="av_section_3" class="avia-section main_color avia-section-default avia-no-shadow avia-bg-style-scroll  avia-builder-el-6  el_after_av_section  avia-builder-el-last  container_wrap fullsize" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-color: rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; clear: both; position: static; width: 1263px; float: left; min-height: 100px; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 240);">
        <div class="container" style="box-sizing: border-box; margin: 0px auto; padding: 0px 50px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1263px; clear: both; max-width: 1310px;">
            <div class="template-page content  av-content-full alpha units" style="box-sizing: content-box; margin: 0px auto; padding: 50px 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; display: inline; position: relative; z-index: 1; min-height: 1px; clear: left; width: 1163px;">
                <div class="post-entry post-entry-type-page post-entry-5754" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                    <div class="entry-content-wrapper clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; zoom: 1;">
                        <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;">
                            <div class="avia_textblock " itemprop="text" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.65em; font-family: inherit; vertical-align: baseline; clear: both;">
                                <h2 style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 36px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(51, 51, 51); text-transform: none; letter-spacing: 1px; text-align: center;">Management&nbsp;Team</h2>
                            </div>
                        </section>
                        <div class="hr hr-short hr-center  avia-builder-el-8  el_after_av_textblock  el_before_av_one_half " style="box-sizing: border-box; margin: 10px 0px 20px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; clear: both; display: block; width: 1163px; height: 20px; position: relative; float: none;">
                            <span class="hr-inner " style="box-sizing: border-box; margin: -1px 0px 0px -186.078px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-color: rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; height: 1px; left: 581.5px; top: 10px; width: 372.156px; background-color: rgb(255, 255, 255);"><span class="hr-inner-style" style="box-sizing: border-box; margin: -5px 0px 0px -5px; padding: 0px; border: 2px solid rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; border-radius: 20px; height: 9px; width: 9px; display: block; position: absolute; left: 186.078px; background-color: rgb(255, 255, 255);"></span></span>
                        </div>
                        <div class="flex_column av_one_half first  avia-builder-el-9  el_after_av_hr  el_before_av_one_half  " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; z-index: 1; float: left; position: relative; min-height: 1px; width: 546.609px; clear: left;">
                            <section class="avia-team-member  avia-builder-el-10  avia-builder-el-no-sibling " itemscope="itemscope" itemtype="https://schema.org/Person" style="box-sizing: border-box; margin: 0px; padding: 20px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; clear: both; background: rgb(255, 255, 255);">
                                <div class="team-img-container" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; overflow: hidden; border-radius: 3px; text-align: center;">
                                    <img alt="pankaj-agarwal Company" class="avia_image avia_image_team     lazyloaded" data-lazy-src="http://www.optimusinfo.com/wp-content/uploads/2014/11/pankaj-agarwal.jpg" itemprop="image" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/pankaj-agarwal.jpg" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; border-radius: 3px; position: relative;" title="pankaj-agarwal Company" /><div class="team-social" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 7px solid rgba(0, 0, 0, 0.0980392); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 19px; line-height: inherit; font-family: inherit; vertical-align: baseline; transition: all 0.3s ease-out; position: absolute; opacity: 0; visibility: hidden; top: 0px; left: 0px; right: 0px; bottom: 0px; text-align: center; border-radius: 3px; background: rgba(255, 255, 255, 0.701961);">
                                        <div class="team-social-inner" style="box-sizing: border-box; margin: -26px 0px 0px; padding: 0px 24.625px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 492.609px; position: absolute; top: 143px; left: 0px;">
                                            <span class="hidden av_member_url_markup  linkedin" itemprop="url" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0px; visibility: hidden;"></span>
                                            <a aria-hidden="true" class=" linkedin avia-team-icon " data-av_icon="" data-av_iconfont="entypo-fontello" data-avia-tooltip="LinkedIn" href="http://ca.linkedin.com/in/pankajoptimus" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://ca.linkedin.com/in/pankajoptimus', '']);" rel="v:url" style="box-sizing: border-box; margin: 3px; padding: 0px 16px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 54px; font-family: inherit; vertical-align: baseline; text-decoration: none; outline: 0px; max-width: 100%; position: relative; border-radius: 30px; display: inline-block; height: 53px; width: 53px; color: rgb(145, 145, 145); background: rgb(255, 255, 255);" target="_blank"></a>
                                        </div>
                                    </div>
                                </div>
                                <h3 class="team-member-name" itemprop="name" style="box-sizing: border-box; margin: 20px 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 1.55em; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">Pankaj Agarwal</h3>
                                <div class="team-member-job-title " itemprop="jobTitle" style="box-sizing: border-box; margin: -7px 0px 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 1em; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                    Founder and Managing Partner</div>
                                <div class="team-member-description " itemprop="description" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                        Pankaj Agarwal is the Managing Partner of Optimus Information Inc. He is an active investor in Canadian, US and Indian startups and private technology companies serving on the boards of a number of companies. Pankaj has over two decades of experience working in the technology outsourcing industry. Before founding Optimus, he was a co-founder and CEO of Momentum Technologies Inc. until they were purchased by the European IT consulting company Sopra Group where he served on the Executive Committee.</p>
                                </div>
                                <span class="hidden team-member-affiliation" itemprop="affiliation" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0px; visibility: hidden;"></span>
                            </section>
                        </div>
                        <div class="flex_column av_one_half   avia-builder-el-11  el_after_av_one_half  el_before_av_one_half  " style="box-sizing: border-box; margin: 0px 0px 0px 69.7656px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; z-index: 1; float: left; position: relative; min-height: 1px; width: 546.609px;">
                            <section class="avia-team-member  avia-builder-el-12  avia-builder-el-no-sibling " itemscope="itemscope" itemtype="https://schema.org/Person" style="box-sizing: border-box; margin: 0px; padding: 20px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; clear: both; background: rgb(255, 255, 255);">
                                <div class="team-img-container" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; overflow: hidden; border-radius: 3px; text-align: center;">
                                    <img alt="vipul-kulshrestha1-300x300 Company" class="avia_image avia_image_team     lazyloaded" data-lazy-src="http://www.optimusinfo.com/wp-content/uploads/2014/11/vipul-kulshrestha1-300x300.jpg" itemprop="image" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/vipul-kulshrestha1-300x300.jpg" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; border-radius: 3px; position: relative;" title="vipul-kulshrestha1-300x300 Company" /><div class="team-social" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 7px solid rgba(0, 0, 0, 0.0980392); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 19px; line-height: inherit; font-family: inherit; vertical-align: baseline; transition: all 0.3s ease-out; position: absolute; opacity: 0; visibility: hidden; top: 0px; left: 0px; right: 0px; bottom: 0px; text-align: center; border-radius: 3px; background: rgba(255, 255, 255, 0.701961);">
                                        <div class="team-social-inner" style="box-sizing: border-box; margin: -26px 0px 0px; padding: 0px 24.625px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 492.609px; position: absolute; top: 143px; left: 0px;">
                                            <span class="hidden av_member_url_markup  linkedin" itemprop="url" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: 0px; visibility: hidden;"></span>
                                            <a aria-hidden="true" class=" linkedin avia-team-icon " data-av_icon="" data-av_iconfont="entypo-fontello" data-avia-tooltip="LinkedIn" href="http://in.linkedin.com/in/vipulkulshrestha" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://in.linkedin.com/in/vipulkulshrestha', '']);" rel="v:url" style="box-sizing: border-box; margin: 3px; padding: 0px 16px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 54px; font-family: inherit; vertical-align: baseline; text-decoration: none; outline: 0px; max-width: 100%; position: relative; border-radius: 30px; display: inline-block; height: 53px; width: 53px; color: rgb(145, 145, 145); background: rgb(255, 255, 255);" target="_blank"></a>
                                        </div>
                                    </div>
                                </div>
                                <h3 class="team-member-name" itemprop="name" style="box-sizing: border-box; margin: 20px 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 1.55em; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">Vipul Kulshrestha</h3>
                                <div class="team-member-job-title " itemprop="jobTitle" style="box-sizing: border-box; margin: -7px 0px 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 1em; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(145, 145, 145);">
                                    Co-Founder &amp; Head of India Operations</div>
                                <div class="team-member-description " itemprop="description" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                                        Vipul Kulshrestha is the Head of India Operations of Optimus Information Inc. Vipul has over 20 years of experience working in technology outsourcing companies including over 15 years in management. Before founding Optimus, he was a Senior Vice President at the Sopra Group and a Program Manager at Momentum Technologies Inc. Vipul has Engineering Degree in Electronics followed by Masters in Computer Science, both from IIT, Roorkee.</p>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
