<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="University.aspx.cs" Inherits="Assignment_15.WebForm7" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    The Optimus Information model is designed to allocate the right mix of local and offshore resources in order to optimize expertise, speed and cost. We provide Outsourcing-as- a-Service (OaaS), the ability for development teams to quickly add specialty skills to a development team without incurring long-term costs. Our global team is made up of well- rounded experienced professionals, allowing us to work on complex solutions requiring diverse expertise. The result for our customers is the capability to far better manage resource capacities and outcomes.</p>
<h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; font-size: 20px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Technical Expertise</h3>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Optimus Information partners with leading technology vendors to provide our clients with the most current solutions in the marketplace. We have technical expertise in the leading open source and proprietary software platforms. Optimus is a Microsoft Gold Partner.<br style="box-sizing: border-box;" />
    <img alt="20 Optimus Advantage" class="alignleft size-full wp-image-7290" height="20" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/20.gif" style="box-sizing: border-box; margin: 4px 10px 0px 0px; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; float: left; position: relative;" title="20 Optimus Advantage" width="1" /></p>
<h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; font-size: 20px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Enterprise Expertise</h3>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Our background in enterprise solutions means we are focused on delivering high-quality software with corporate impact. Optimus has experience working with regulatory requirements and standards such as HIPPA, PCI, SOX, CMMI and ISO.<br style="box-sizing: border-box;" />
    <img alt="20 Optimus Advantage" class="alignleft size-full wp-image-7290" height="20" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/20.gif" style="box-sizing: border-box; margin: 4px 10px 0px 0px; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; float: left; position: relative;" title="20 Optimus Advantage" width="1" /></p>
<h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; font-size: 20px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Hybrid Delivery Model</h3>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Our model is designed to allocate the right mix of local and offshore resources in order to optimize expertise and speed to help clients around the world. With offices in North America and India, Optimus has the capability to design, develop, test, deploy and support complex systems wherever they are needed.<br style="box-sizing: border-box;" />
    <img alt="20 Optimus Advantage" class="alignleft size-full wp-image-7290" height="20" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/20.gif" style="box-sizing: border-box; margin: 4px 10px 0px 0px; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; float: left; position: relative;" title="20 Optimus Advantage" width="1" /></p>
<h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; font-size: 20px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Scalability</h3>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Our model gives clients a scalable partner that can help manage risks during various development stages. We can scale resources quickly in short notice and bring a variety of expertise to the table as needed. Clients often require part-time assistance from several different types of experts – we offer this kind of flexibility.<br style="box-sizing: border-box;" />
    <img alt="20 Optimus Advantage" class="alignleft size-full wp-image-7290" height="20" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/20.gif" style="box-sizing: border-box; margin: 4px 10px 0px 0px; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; float: left; position: relative;" title="20 Optimus Advantage" width="1" /></p>
<h3 style="box-sizing: border-box; margin: 1.5em 0px 8px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: 600; font-stretch: inherit; font-size: 20px; line-height: 1.1em; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(251, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Engagement Process</h3>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    <img alt="engagement-process Optimus Advantage" class="alignleft size-full wp-image-7288" height="179" sizes="(max-width: 747px) 100vw, 747px" src="http://www.optimusinfo.com/wp-content/uploads/2014/11/engagement-process.jpg" srcset="http://www.optimusinfo.com/wp-content/uploads/2014/11/engagement-process.jpg 747w, http://www.optimusinfo.com/wp-content/uploads/2014/11/engagement-process-300x72.jpg 300w, http://www.optimusinfo.com/wp-content/uploads/2014/11/engagement-process-705x169.jpg 705w, http://www.optimusinfo.com/wp-content/uploads/2014/11/engagement-process-450x108.jpg 450w, http://www.optimusinfo.com/wp-content/uploads/2014/11/engagement-process-200x48.jpg 200w" style="box-sizing: border-box; margin: 4px 10px 0px 0px; padding: 0px; border: none rgb(225, 225, 225); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; max-width: 100%; height: auto; float: left; position: relative;" title="engagement-process Optimus Advantage" width="747" /></p>
</asp:Content>
